name: run-md-to-html

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Cyberculture and Social Justice Directory.md'
      - 'AboutPage.md'
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python scripts/markdown_to_html.py

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v8.8
        id: verify-changed-files
        with:
          files:
             '*.html'

      - name: commit html files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '*.html'
          git commit -m "Automatic update HTML files" -a

      - name: push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${GITHUB_REF##*/}
